// ─── DigiLing Static Feedback Service ────────────────────────────────────────
// Provides pre-written response pools that simulate AI-generated feedback.
// Used as fallback when Gemini API is unavailable, or as the primary feedback
// source in demo / offline mode.
// ─────────────────────────────────────────────────────────────────────────────

// ─── Response Pools ──────────────────────────────────────────────────────────

const READING_RESPONSES = {
  excellent: [
    "You scored excellently on this passage. At this level, the next skill to develop is reading between the lines — called inferencing. Authors do not always state everything directly. Practice asking yourself: What is the author implying but not directly saying?\n\nExercise: Read a short editorial article daily and write down 2 implied meanings that are not directly stated in the text. This trains your brain for C1 level reading tasks.",
    "Great score! Now focus on reading speed without losing comprehension. Most students at this level read too slowly which causes them to lose track of earlier details by the time they reach the questions.\n\nTechnique: Use the skimming method. Read the questions FIRST before reading the passage. This trains your brain to look for specific information as you read instead of trying to remember everything.\n\nExercise: Time yourself reading a passage. Aim to answer all questions within 10 minutes for a 300-word text.",
    "Excellent comprehension! The area to work on next is understanding vocabulary in context. At higher CEFR levels, passages contain academic words you may not know. You do not need to know every word — you need to guess meaning from surrounding sentences.\n\nTechnique: When you see an unknown word, read the full sentence and the sentence before and after it. The context usually gives strong clues about the meaning.\n\nExercise: Read one academic article daily and underline 5 unknown words. Try guessing their meaning from context BEFORE checking a dictionary.",
    "Outstanding result! Now challenge your ability to identify the author's purpose. Every passage is written with a reason — to inform, persuade, entertain, or describe. Identifying this purpose helps you answer tone and attitude questions correctly.\n\nTechnique: After reading any text, ask: Why did the author write this? What do they want me to think or feel?\n\nExercise: Read 3 short passages this week and label each one as: informative, persuasive, descriptive, or narrative. Write one sentence explaining your choice.",
    "Excellent work! Focus now on distinguishing facts from opinions in a passage. This is a common question type in B2 to C2 level reading tests that many students get wrong.\n\nTechnique: Facts can be proven. Opinions use words like: should, believe, think, feel, seem, appear, arguably, and in my view. Train yourself to spot these signal words immediately.\n\nExercise: Take any news article and highlight facts in one color and opinions in another. Do this daily for one week."
  ],
  good: [
    "Good score! The questions you likely missed were detail-based rather than main idea questions. This is very common at this level.\n\nThe problem: Students read for general understanding but questions ask for specific details like exact numbers, names, or sequence of events.\n\nTechnique: After reading each paragraph, pause and mentally summarize: Who? What? Where? When? This forces you to retain details as you read.\n\nExercise: Read a short passage and after every paragraph write one sentence summarizing the key detail. Do not move to the next paragraph until you can do this.",
    "Nice result! A common issue at this score range is misreading questions. Students understand the passage well but choose wrong answers because they misread what the question is asking.\n\nTechnique: Underline the KEY word in every question before looking for the answer. For example in the question 'What is the MAIN reason the author mentions climate change?' — the key word is MAIN REASON not just climate change.\n\nExercise: Before answering any question, circle the most important word in it. This takes 5 extra seconds but significantly improves accuracy.",
    "Good performance! You likely understood the passage well but lost points on inference questions — questions where the answer is NOT directly written in the text.\n\nThese questions use phrases like: It can be inferred, The author suggests, or It is implied that.\n\nTechnique: For inference questions go back to the relevant paragraph. Ask: What does this paragraph suggest without directly saying? Choose the answer that logically follows from the text.\n\nExercise: After reading any passage, write 2 things the author implied but never directly stated.",
    "Well done! Work on managing your time better during reading tasks. Many students at this level spend too long on early questions and rush through the final ones — causing avoidable mistakes at the end.\n\nTechnique: Give yourself a time limit per question. For a 10-question quiz, spend maximum 1.5 minutes per question. If unsure, mark it and move on. Come back to it after finishing the rest.\n\nExercise: Practice timed reading this week. Set a 15-minute timer for each reading activity and stick to it.",
    "Good score! To push into the 90 percent range focus on understanding paragraph structure. Each paragraph in a well-written passage has a topic sentence that states the main idea and supporting sentences that explain or give examples.\n\nTechnique: Identify the topic sentence of each paragraph (usually first or last sentence). Understanding these gives you a map of the entire passage before you even read the details.\n\nExercise: For every passage you read this week, underline only the topic sentence of each paragraph. Then check if you can understand the passage just from those underlined sentences alone."
  ],
  practice: [
    "You are developing your reading skills. At this score level the most common issue is reading word by word instead of in phrases. This makes reading slow and causes you to forget earlier parts of the passage.\n\nTechnique: Train your eyes to read groups of words together. For example instead of reading: The | cat | sat | on | the | mat — read it as: The cat | sat on | the mat.\n\nExercise: Take any paragraph and draw slash marks to divide it into word groups. Practice reading each group as one unit. Do this for 10 minutes daily.",
    "Keep practicing! A key issue at this level is not knowing enough vocabulary to understand the full passage. Unknown words break your reading flow and cause you to lose meaning.\n\nTechnique: Build a personal vocabulary list. Every time you read and find an unknown word, write it down with its meaning and an example sentence. Review this list every morning.\n\nExercise: Learn 5 new English words every day. Write them in a notebook, look up their meaning, and write one sentence using each word. After 30 days you will know 150 new words.",
    "You are improving! One reason for this score range is re-reading too much. Students go back to re-read the same sentence many times which wastes time and causes confusion.\n\nTechnique: Read each sentence only once with full attention. If you did not understand it, move forward anyway. The next sentences often clarify what came before.\n\nExercise: Force yourself to read a passage WITHOUT going back. After finishing, answer the questions from memory. This trains your brain to focus better the first time.",
    "Good effort! At this score level, students often do not understand what the question is asking before they search for the answer.\n\nTechnique: Before scanning the passage for an answer, translate the question in your head into simpler words. For example: 'What does the author attribute the decline to?' simply means 'What does the author say caused the decline?'\n\nExercise: Take 5 comprehension questions and rewrite each one in simpler English. This trains you to understand complex academic question language.",
    "You completed the activity! The main skill to build right now is finding the main idea of a passage. Many students focus on small details and miss the overall message.\n\nTechnique: Before reading the questions, read the TITLE and FIRST PARAGRAPH only. Ask yourself: What is this passage about? This gives you a frame before you dive into the details.\n\nExercise: Read the first paragraph of 5 different articles this week. For each one write one sentence: This passage is about [topic] and the author's main point is [main idea]."
  ],
  dontGiveUp: [
    "Thank you for completing this activity! This level may currently be above your reading level and that is completely fine.\n\nThe most important thing to fix first is building your reading vocabulary. Without knowing the words you cannot understand the sentences.\n\nTechnique: Start reading texts at A1 or A2 level where you understand at least 90 percent of the words. Struggling with too many unknown words at once builds frustration not skill.\n\nExercise: Download a free graded reader app like Oxford Reading Tree or British Council LearnEnglish. Start at the lowest level and work upward systematically.",
    "Keep going! Reading in English is genuinely hard and your effort matters.\n\nThe biggest barrier at this stage is likely sentence structure. English uses Subject Verb Object order but longer sentences add clauses and phrases that break this pattern.\n\nTechnique: When you find a confusing sentence, find the MAIN verb first. The main verb tells you the core action. Everything else modifies that action.\n\nExercise: Take 5 complex sentences from any English text. Identify and underline only the subject and main verb. Strip away everything else and check if the basic meaning is clearer.",
    "Good effort for trying! Consider practicing at A1 level first to build a strong foundation.\n\nOne specific skill to focus on: understanding pronouns in text. Words like it, they, this, that, and which refer back to something mentioned earlier. Students often lose the meaning of a passage because they do not track what these words refer to.\n\nTechnique: Every time you see a pronoun while reading, pause and ask: What does this word refer to? Draw an arrow back to its reference.\n\nExercise: Take a paragraph and circle every pronoun. Draw lines connecting each pronoun to the noun it replaces.",
    "You showed determination by finishing! A great starting point right now is working on reading short simple texts consistently rather than difficult ones occasionally.\n\nTechnique: The 5 finger rule. While reading if you find 5 or more unknown words on one page the text is too difficult for you right now. Choose a simpler text. Comfortable reading builds skill faster than struggling through hard texts.\n\nExercise: Read one simple English paragraph every morning. Write a one-sentence summary of what you read. Simple and consistent beats difficult and occasional.",
    "Every attempt builds your skill! At this stage focus on reading for the overall meaning rather than understanding every word.\n\nTechnique: The 70 percent rule. If you understand 70 percent of a sentence that is enough to grasp the meaning. Do not stop at every unknown word. Keep reading and let context fill the gaps.\n\nExercise: Read a simple English paragraph without stopping for unknown words. At the end write what you think the paragraph was about in your own language first, then try in English."
  ]
};

const WRITING_RESPONSES = {
  excellent: [
    "Excellent writing! To reach C1 level focus on cohesion — how well your sentences connect to each other. Strong writers do not just write correct sentences, they link ideas smoothly across paragraphs.\n\nTechnique: Use discourse markers deliberately. Instead of starting every sentence with I or The, use linking phrases like: Furthermore, As a result, In contrast, Despite this, and This suggests that.\n\nExercise: Take your submitted response and rewrite it adding at least 3 discourse markers between sentences. Check how the flow improves.",
    "Outstanding work! The next writing skill to master is varying your sentence structure. Writing only in simple or compound sentences limits your score at C1 and C2 levels.\n\nTechnique: Mix three sentence types:\nSimple: one main clause\nCompound: two clauses joined by and but or\nComplex: main clause plus subordinate clause using because although while since if\n\nExercise: Write 9 sentences about any topic — 3 simple, 3 compound, 3 complex. This trains your brain to naturally vary sentence structure.",
    "Great writing! Work on making your topic sentences stronger. The topic sentence is the most important sentence in a paragraph. A weak topic sentence makes the whole paragraph unclear.\n\nTechnique: A strong topic sentence states the MAIN POINT of the paragraph in one clear sentence. It should not be a fact — it should make a CLAIM that the rest of the paragraph supports.\n\nWeak: Many people use social media.\nStrong: Social media has significantly changed how people communicate in the modern world.\n\nExercise: Rewrite your topic sentences from this activity making each one a clear claim rather than a simple fact.",
    "Impressive writing! To push your score higher focus on word precision. Strong writers choose words that convey the exact meaning they want rather than using general words.\n\nTechnique: Replace general words with precise ones:\nsaid → argued, suggested, claimed, emphasized, noted, stated\ngood → effective, beneficial, significant, valuable\nbad  → harmful, detrimental, inadequate, problematic\n\nExercise: Go through your written response and replace every general word with a more precise one. A thesaurus can help but make sure you understand the word you choose.",
    "Excellent work! The final skill to polish is your conclusion. Many students end their writing abruptly or just repeat their introduction word for word.\n\nTechnique: A strong conclusion does three things in 2-3 sentences:\n1. Restates the main point in NEW words — not copied from intro\n2. Summarizes the key supporting points\n3. Ends with a final thought, recommendation, or forward-looking statement\n\nExercise: Rewrite the conclusion of your submitted response using these three steps. Compare it to your original and notice the difference."
  ],
  good: [
    "Good writing! The most likely reason for missed points is grammar consistency especially with verb tenses. Filipino students commonly mix present and past tense within the same paragraph.\n\nTechnique: Before submitting any writing decide on your TENSE first. If writing about a past event use past tense throughout. If describing a general truth use present tense. Do not switch between them.\n\nExercise: Read your submitted response aloud and circle every verb. Check that all verbs are in the same tense. Correct any that are inconsistent.",
    "Nice work! A common issue at this score range is using the same word repeatedly in one paragraph. This makes writing feel repetitive and limits your vocabulary score.\n\nTechnique: The No-Repeat Rule. Try not to use the same content word more than twice in one paragraph. Use synonyms, pronouns, or restructure the sentence to avoid repetition.\n\nExercise: Read your submitted response and highlight any word you used more than twice. Replace repeated words with synonyms. Use a free thesaurus at thesaurus.com",
    "Well done! Work on paragraph organization. At this score level students often write good ideas but in the wrong order making the writing hard to follow.\n\nTechnique: Use the PEEL structure for every paragraph:\nP — Point: State your main idea\nE — Evidence: Give a reason or example\nE — Explain: Explain how it supports your main point\nL — Link: Connect to the next paragraph or your overall argument\n\nExercise: Restructure one paragraph from your submitted response using the PEEL format. Notice how much clearer it becomes.",
    "Good effort! The issue is likely with articles and prepositions — specifically a, an, the, in, on, at, by, for, with. These are the most common grammar errors for Filipino writers in English.\n\nSpecific rules to memorize:\nUse THE for specific nouns already mentioned or known to both reader and writer.\nUse A or AN for non-specific nouns mentioned for the first time.\nUse NO article for plural general nouns.\nExample: A dog ran into the room. The dog was barking loudly.\n\nExercise: Find 10 nouns in your written response and check if the article before each one is correct.",
    "Great composition! To improve further work on your introduction. A strong introduction does three things:\n1. Hooks the reader with an interesting opening sentence (question, fact, or bold statement)\n2. Provides brief background context\n3. States your main point clearly\n\nWeak intro: This essay is about environmental problems.\nStrong intro: Every year millions of tons of plastic enter our oceans — a crisis that demands immediate action from individuals and governments alike.\n\nExercise: Rewrite your introduction using this three-part structure."
  ],
  practice: [
    "Good effort! The most impactful thing to fix right now is subject-verb agreement. This is one of the most frequent errors in this score range and fixing it alone can significantly improve your score.\n\nRule: Singular subjects take singular verbs. Plural subjects take plural verbs.\nWrong: The students was happy.\nRight: The students were happy.\n\nTricky cases:\nEveryone, someone, nobody → singular verb\nEveryone IS ready. Not everyone ARE ready.\n\nExercise: Write 10 sentences making sure each subject and verb agree. Mix singular and plural subjects. Check each one carefully.",
    "Keep going! Focus on writing complete sentences. A fragment is an incomplete sentence — it is missing a subject, a verb, or both. Fragments are one of the most common errors at this level.\n\nFragment: Because I was tired.\nComplete: I went home early because I was tired.\n\nFragment: Running to school every day.\nComplete: She runs to school every day.\n\nRule: Every sentence must have a subject (who does the action) and a main verb (the action itself).\n\nExercise: Check every sentence in your response. Can you find the subject and the verb in each one? If not, rewrite it.",
    "Nice effort! Work on using punctuation correctly especially commas and periods. Missing or misplaced punctuation changes the meaning of sentences and makes writing hard to read.\n\nKey comma rules:\n1. Use a comma before and but or when joining two complete sentences\n2. Use a comma after introductory phrases like: However, In addition, As a result, Although I was tired\n3. Use a comma to separate items in a list: red, blue, and green\n\nExercise: Read your response aloud. Every time you naturally pause put a comma. Every time you stop put a period. Compare to your original.",
    "Good start! Your ideas are there but they need clearer structure. Writing without structure is like building a house without a floor plan.\n\nTechnique: Before writing always make a quick outline:\nIntroduction — What am I writing about?\nBody 1 — First main point + example\nBody 2 — Second main point + example\nConclusion — Summary + final thought\n\nExercise: For your next writing task spend 2 minutes making a simple outline before you write a single sentence. Structured thinking produces structured writing.",
    "You are on the right track! The most useful thing to practice now is writing simple clear sentences before attempting complex ones.\n\nA common mistake is writing long confusing sentences when trying to sound advanced. Clear and simple is always better than complex and unclear.\n\nTechnique: The 20-word rule. If a sentence is longer than 20 words consider splitting it into two sentences. Long sentences are hard to control grammatically.\n\nExercise: Find your longest 3 sentences from this activity and split each one into two shorter clearer sentences."
  ],
  dontGiveUp: [
    "Thank you for submitting! The foundation to build first is basic sentence construction.\n\nEvery English sentence follows this basic pattern:\nSubject + Verb + Object (Optional)\n\nI (S) eat (V) rice (O).\nShe (S) studies (V) English (O).\nThey (S) played (V) basketball (O).\n\nExercise: Write 10 sentences every day following this exact pattern. Start with simple everyday topics like food, school, and family. Master this structure before adding more complexity.",
    "Keep trying! Right now focus on ONE grammar rule per week rather than trying to fix everything at once.\n\nStart with: Simple Present Tense\nUse it for: habits, facts, routines\nStructure: Subject + base verb (+ s for he/she/it)\n\nI study. She studies. They study.\nHe eats. We eat. It rains.\n\nExercise: Write 5 sentences about your daily routine using simple present tense. Check that you added S to verbs after he, she, it. One grammar rule mastered per week adds up to 52 rules per year.",
    "Great courage for submitting! Start building your writing habit with a simple daily journal.\n\nWrite 3 sentences in English every night about your day:\nSentence 1: What you did today\nSentence 2: How you felt about it\nSentence 3: What you will do tomorrow\n\nThis is called structured journaling and it builds writing fluency faster than any textbook exercise because you write about something you actually know and experienced.\n\nDo this every night for 30 days.",
    "You showed effort by completing this! The most important writing skill to build at this stage is spelling common English words correctly.\n\nMost misspelled words by Filipino students: because, environment, which, people, their, there, they are, definitely, separate, necessary, government, beautiful.\n\nTechnique: The Look-Cover-Write-Check method. Look at a word, cover it, write it from memory, then check.\n\nExercise: Practice spelling 5 of the words above using this method daily until you can spell them automatically.",
    "Every submission is practice! To improve your writing start by copying good English sentences and then imitating their structure.\n\nTechnique: Sentence imitation. Find a well-written English sentence, study its structure, then write your own sentence following the same pattern.\n\nExample sentence: Despite the heavy rain, the students arrived at school on time.\n\nYour imitation: Despite the difficult exam, the student finished all the questions with confidence.\n\nExercise: Find 3 good sentences this week and write your own version following each one's structure exactly."
  ]
};

const LISTENING_RESPONSES = {
  excellent: [
    "Excellent listening! To improve further train yourself to listen for discourse markers in spoken English. These are spoken signals that tell you what comes next in a conversation.\n\nKey signal words to listen for:\nCONTRAST: however, on the other hand, but, although, despite\nADDITION: furthermore, in addition, also, moreover\nCAUSE: because, since, as a result, therefore, consequently\nSEQUENCE: first, then, after that, finally, subsequently\n\nExercise: Listen to a 2-minute English podcast and tally how many discourse markers you hear. This sharpens your ear for the structure of spoken language.",
    "Great score! The next skill to develop is listening for speaker attitude and tone. Questions about how someone feels or what they imply are the hardest in listening tests.\n\nTechnique: Pay attention to these tone indicators in spoken English:\nHesitation (um, uh, well) → uncertain\nRising intonation → questioning or unsure\nEmphasis on specific words → importance\nSlower speech on key points → emphasis\n\nExercise: Watch a 5-minute English interview video. After each speaker turn, write one word describing their attitude: confident, unsure, excited, worried, sarcastic.",
    "Outstanding listening! Focus now on understanding accents other than the one you are most familiar with. At C1 level listening tests include British, American, Australian, and other English accents.\n\nKey differences to practice:\nBritish: can't sounds like cahnt, water sounds like wah-tah\nAmerican: T between vowels sounds like D, better sounds like bedder\nAustralian: today sounds like tuh-dye\n\nExercise: Listen to the same news story from BBC (British), CNN (American), and ABC Australia. Notice how pronunciation differs for the same words.",
    "Impressive result! Work on listening for numbers, dates, and statistics in audio. These details are commonly tested and students often miss them because they are focused on the general meaning.\n\nTechnique: When listening, always have a mental notepad ready for:\nDates and years, Prices and percentages, Addresses and phone numbers, Measurements and quantities\n\nExercise: Listen to a weather forecast or news report and write down every number you hear. Check your accuracy by replaying the audio.",
    "Excellent comprehension! The area to sharpen now is understanding indirect speech and reported speech in audio.\n\nDirect: She said I am tired.\nReported: She said she was tired.\n\nIn advanced listening the speaker often reports what someone else said which shifts the tense. This confuses many learners.\n\nExercise: Listen to a 2-minute audio where someone tells a story. Write down 3 things they reported that another person said. Practice identifying the tense shift."
  ],
  good: [
    "Good listening! The questions you missed were likely detail questions about specific information in the audio. This happens because listeners focus on understanding overall meaning and miss specific facts.\n\nTechnique: Predictive listening. Before the audio plays read the questions carefully. Underline the key word in each question. Then as you listen your brain actively searches for that specific piece of information.\n\nExercise: Before any listening task, spend 30 seconds reading ALL the questions first. Then listen. Practice this until it becomes habit.",
    "Nice score! Work on listening to the end of sentences before forming your answer. Many students decide on an answer midway through a sentence but English sentences often have negatives or qualifiers at the end that completely change the meaning.\n\nExample: I was going to go to the party... but I decided to stay home.\n\nA student who stopped listening after party would choose the wrong answer.\n\nExercise: Listen to 5 English sentences. Do NOT form your answer until the sentence is completely finished.",
    "Good performance! Improve your ability to listen and take notes simultaneously. At this score level students often miss answers because they cannot hold information in memory long enough to answer the question.\n\nTechnique: Shorthand notes. Create your own abbreviations for common words:\nimp = important, info = information, bc = because, esp = especially, govt = government, env = environment\n\nExercise: Listen to a 1-minute audio and write shorthand notes as you listen. Then answer questions from your notes without replaying the audio.",
    "Well done! A common issue at this score range is confusing similar-sounding words called minimal pairs. These cause wrong answers in detail questions.\n\nCommon minimal pairs:\nship / sheep, live / leave, bit / beat, sit / seat, fill / feel, hill / heel, eighteen / eighty, thirteen / thirty\n\nExercise: Find a minimal pairs listening exercise online (many free ones on British Council website). Practice identifying these word pairs by ear daily for one week.",
    "Good effort! Train yourself to understand fast natural speech. In natural English words connect and blend together — this is called connected speech.\n\nCommon connected speech patterns:\nwant to → wanna\ngoing to → gonna\nkind of → kinda\nlet me → lemme\ndid you → didja\nwhat are you → whatcha\n\nThese are not slang — they are natural pronunciation features of fast English speech.\n\nExercise: Watch 5 minutes of an American TV show or YouTube video without subtitles. Write down 3 words or phrases that sounded different from how they are written."
  ],
  practice: [
    "Keep practicing! The biggest barrier at this score level is usually listening speed. Natural English is spoken at 150 to 180 words per minute which is much faster than most learners are used to.\n\nTechnique: Start slow, build up. On YouTube and most video players you can reduce playback speed to 0.75x. Listen at reduced speed first until you can understand 90 percent. Then gradually increase to normal speed.\n\nExercise: Watch a 3-minute YouTube video at 0.75x speed this week. Next week try 1x speed on the same video. Notice how much more you understand the second time.",
    "Good try! Work on expanding your listening vocabulary. You can only understand what you already know. If a word is unfamiliar in text it will be even harder to catch in fast spoken audio.\n\nTechnique: Reading and listening together. Read a text version of content first then listen to the audio version of the same content. This bridges reading and listening vocabulary.\n\nExercise: Find a BBC Learning English audio lesson. Read the transcript first then listen without the transcript. Do this 3 times per week.",
    "Nice effort! Focus on identifying the topic of an audio within the first 10 seconds. The opening of any audio almost always states or strongly implies the topic. Missing this means the rest of the audio has no frame of reference.\n\nTechnique: The first 10 seconds rule. Whatever is mentioned first is almost always what the whole audio is about. Use this to predict what vocabulary and topics will follow.\n\nExercise: Listen to 5 audio clips and after exactly 10 seconds pause and write what you think the full audio will be about. Then continue listening to check your prediction.",
    "You are developing your listening skills! A practical exercise for this score range is dictation practice.\n\nTechnique: Dictation training. Listen to a slow English audio. Pause after every sentence and write exactly what you heard. Check your written version against the transcript. This trains your ear and your brain to process spoken words more accurately.\n\nExercise: Do one dictation exercise every day for 2 weeks. Even 5 minutes daily produces significant improvement in listening accuracy.",
    "Good effort! At this level the most useful thing is massive listening input — simply hearing a lot of English every day.\n\nResearch shows that learners need hundreds of hours of listening input before comprehension becomes natural. The goal is to make English sounds familiar to your brain.\n\nTechnique: Background listening. Play English audio at a comfortable level while doing other activities like eating or household tasks. Even passive listening builds familiarity with English rhythm and sounds.\n\nExercise: Keep English audio playing in the background for at least 30 minutes every day this week."
  ],
  dontGiveUp: [
    "Thank you for completing this task! At this stage the priority is making English sounds familiar to your ears.\n\nEnglish has sounds that do not exist in Filipino such as the V sound, the TH sound, and the short I sound as in sit versus the long EE sound in seat.\n\nTechnique: Phonics practice. Learn the 44 sounds of English (called phonemes) not just the 26 letters. Many free phonics charts are available online.\n\nExercise: Search for English phonics chart on Google Images. Practice saying each of the 44 sounds daily for 5 minutes. Focus especially on sounds that do not exist in Filipino.",
    "Keep trying! Start with the most accessible free English listening resource: English subtitled videos.\n\nTechnique: Active subtitle watching. Watch a simple English video with English subtitles (not Filipino). Cover the subtitles and try to understand. Uncover to check. Rewind and listen again. The subtitle gives you immediate feedback on what you missed.\n\nExercise: Watch one 5-minute YouTube video this way every day. TED-Ed and BBC Learning English have good free content with subtitles.",
    "Good effort for trying! Start building your listening foundation with very slow English.\n\nThe best free resource for this level: Voice of America Learning English (learningenglish.voanews.com). They broadcast news at 60 percent normal speed with simple vocabulary — specifically designed for English learners.\n\nExercise: Listen to one 3-minute VOA Learning English story daily. After listening write 3 things you understood. After one month compare your first entry to your most recent one.",
    "You showed courage by completing this! Focus on recognizing the most common 400 English words by ear. These words make up about 70 percent of all spoken English. If you know them by sound you will understand most conversations.\n\nThese include: the, be, to, of, and, a, in, that, have, it, for, not, on, with, he, as, you, do, at, this.\n\nExercise: Search for Dolch word list audio online. Listen to these words being spoken and repeat each one. Learning to recognize these by ear alone will dramatically improve your listening comprehension.",
    "Every listening attempt builds your ear for English! The key at this stage is patience and repetition.\n\nTechnique: Shadowing. Listen to a short English sentence then immediately repeat it out loud trying to mimic the exact pronunciation, rhythm, and speed of the speaker. Shadowing builds both listening and speaking skills simultaneously.\n\nExercise: Find a 1-minute slow English audio clip. Shadow every sentence — listen then immediately repeat. Do this with the same clip daily for one week until you can shadow it perfectly."
  ]
};

const SPEAKING_RESPONSES = {
  long: [
    "Good speaking attempt! The most important speaking skill to develop next is using fillers strategically. Natural English speakers use thinking phrases to maintain fluency while organizing their thoughts.\n\nUse these instead of silence or um:\nThat is a great question...\nWhat I mean is...\nLet me think about that...\nTo be more specific...\nWhat I find interesting is...\n\nExercise: Practice giving a 1-minute talk about any topic using at least 3 of these phrases naturally. Record yourself and listen back.",
    "Nice speaking effort! Work on sentence variety in your spoken responses. Speakers who use only short simple sentences sound less fluent than those who vary their sentence length.\n\nTechnique: The 3-sentence rule. When making a point speak in groups of 3 sentences:\n1. State your point\n2. Give a reason or example\n3. Connect it back to the main topic\n\nExample:\nI enjoy reading. (point)\nIt helps me learn new vocabulary and ideas. (reason)\nBecause of this my English has improved a lot. (connection)\n\nPractice this structure in your next speaking response.",
    "Good spoken response! Focus on pronunciation of consonant clusters — groups of consonants together which are commonly mispronounced by Filipino speakers of English.\n\nCommon clusters to practice:\nstr: street, strong, straight, strange\nspr: spring, spread, sprite, express\nthr: three, through, throw, thread\nspl: split, splash, splendid, splay\n\nTechnique: Practice each cluster in isolation first: str str str. Then add a vowel: stra stra stra. Then the full word: straight.\n\nExercise: Record yourself saying 5 words with each cluster above. Listen back and compare to a dictionary pronunciation.",
    "Well done on your recording! The next speaking skill to improve is intonation — the rise and fall of your voice.\n\nEnglish uses intonation to convey meaning beyond words:\nRising intonation → question or uncertainty\nFalling intonation → statement or certainty\nRise-fall pattern → contrast or sarcasm\n\nFlat intonation (same level throughout) makes speech sound robotic and is a common issue for Filipino English speakers.\n\nExercise: Read 5 sentences aloud — 2 statements, 2 questions, 1 expressing surprise. Exaggerate the intonation deliberately. Record yourself and listen to the natural rise and fall.",
    "Great speaking response! Work on word stress within sentences. In English specific words in a sentence carry more stress than others — and changing the stress changes meaning.\n\nI did not take HIS book. (I took someone else's book)\nI did NOT take his book. (I did not take it — someone else did)\nI DID not take his book. (Strong denial — yes I am sure)\n\nTechnique: In any sentence you speak decide which word carries the most important information and stress it slightly more than the others.\n\nExercise: Say the sentence 'I never said she stole the money' seven times, stressing a different word each time. Notice how the meaning shifts."
  ],
  short: [
    "Good start on recording! To develop longer spoken responses use the PREP framework:\n\nP — Point: State your main answer\nR — Reason: Why do you think that?\nE — Example: Give a real example from your life\nP — Point again: Restate your answer\n\nExample for 'Talk about your hobby':\nI enjoy playing basketball. (Point)\nI like it because it keeps me active and I enjoy teamwork. (Reason)\nEvery weekend I play with my friends at the barangay court. (Example)\nThat is why basketball is my favorite hobby. (Point again)\n\nPractice this structure for your next recording attempt.",
    "Nice effort on recording! Speaking longer takes confidence and preparation. A practical technique is the Think-Pair-Share method adapted for solo practice.\n\nBefore recording:\nStep 1 — THINK: Spend 30 seconds thinking about 3 things you want to say\nStep 2 — PLAN: Quickly note keywords not full sentences — just idea words\nStep 3 — SPEAK: Use your keywords as anchors for your response\n\nExercise: For your next attempt spend 30 seconds planning with 3 keywords before pressing record. Most speakers improve significantly with even this small amount of advance planning.",
    "Good effort for recording! Build your spoken fluency with a daily 1-minute speaking exercise.\n\nEvery morning choose one of these simple topics and speak for 1 full minute without stopping:\n- What I ate for breakfast\n- What I did yesterday\n- My favorite place in our city\n- A person I admire and why\n- The last movie or show I watched\n\nTechnique: If you run out of things to say do not stop. Describe the same idea in different words or give another example. Fluency is about maintaining speech flow not about saying new ideas.",
    "Thank you for recording! The most effective exercise for building longer responses is called the 5 Whys technique.\n\nWhen given a topic keep asking WHY to generate more content:\nTopic: My favorite food is adobo.\nWhy? Because it tastes delicious.\nWhy? Because of the vinegar and soy sauce.\nWhy do I like that combination? Because it reminds me of home.\nWhy does it remind me of home? Because my mother cooks it every Sunday.\n\nEach WHY gives you one more sentence to say. Use this to extend any speaking response from 2 sentences to a full paragraph.",
    "Good courage for submitting! Build your speaking vocabulary by learning chunked phrases rather than individual words. Chunks are ready-made groups of words used together naturally.\n\nUseful speaking chunks:\nThe main reason is...\nWhat I mean by this is...\nFor example, in my experience...\nOn the other hand...\nI strongly believe that...\nThis is important because...\nTo sum up my point...\n\nExercise: Choose 3 chunks from this list and use each one in a sentence today. Tomorrow use them in a 30-second response about any topic."
  ]
};

// ─── Score Bracket Helper ─────────────────────────────────────────────────────

function getBracket(pct) {
  if (pct >= 90) return 'excellent';
  if (pct >= 75) return 'good';
  if (pct >= 50) return 'practice';
  return 'dontGiveUp';
}

function pickRandom(arr) {
  return arr[Math.floor(Math.random() * arr.length)];
}

// ─── Public API ───────────────────────────────────────────────────────────────

/**
 * Return a static feedback string for the given skill and score.
 *
 * @param {'reading'|'writing'|'listening'|'speaking'} skill
 * @param {number} score        Correct answers (quiz) or proxy score
 * @param {number} total        Total possible (quiz) or proxy total
 * @returns {string}
 */
export function getStaticFeedback(skill, score, total) {
  const pct = total > 0 ? Math.round((score / total) * 100) : 50;

  switch (skill.toLowerCase()) {
    case 'reading': {
      const pool = READING_RESPONSES[getBracket(pct)];
      return pickRandom(pool);
    }
    case 'writing': {
      const pool = WRITING_RESPONSES[getBracket(pct)];
      return pickRandom(pool);
    }
    case 'listening': {
      const pool = LISTENING_RESPONSES[getBracket(pct)];
      return pickRandom(pool);
    }
    case 'speaking': {
      // score = word count in transcript
      if (score >= 31) return pickRandom(SPEAKING_RESPONSES.long);
      return pickRandom(SPEAKING_RESPONSES.short);
    }
    default:
      return pickRandom(READING_RESPONSES.good);
  }
}

// Loading message steps (ms offset → message)
export const LOADING_MESSAGES = [
  { delay: 0, text: '✦ Analyzing your response...' },
  { delay: 1000, text: '✦ Checking your answers...' },
  { delay: 2000, text: '✦ Generating personalized feedback...' },
  { delay: 3500, text: '✦ Almost done...' },
];

const TOTAL_DELAY_MS = 5000; // Total fake loading time

/**
 * Simulate an AI loading sequence then call onComplete with static feedback.
 *
 * @param {'reading'|'writing'|'listening'|'speaking'} skill
 * @param {number} score
 * @param {number} total
 * @param {(message: string) => void} onMessage  Called on each loading step
 * @param {(feedback: string) => void} onComplete Called when done
 * @returns {() => void} Cleanup function to cancel if component unmounts
 */
export function simulateAIFeedback(skill, score, total, onMessage, onComplete) {
  const timers = [];

  LOADING_MESSAGES.forEach(({ delay, text }) => {
    timers.push(setTimeout(() => onMessage(text), delay));
  });

  timers.push(setTimeout(() => {
    const feedback = getStaticFeedback(skill, score, total);
    onComplete(feedback);
  }, TOTAL_DELAY_MS));

  return () => timers.forEach(clearTimeout);
}
